### PR TITLE
Added helpful links to readme.md

### PR DESCRIPTION
**Pull request by SneakySensei**

### CODE REVIEW

**Review by tnmygrwl — COMMENTED** [review]
Hey @sneakySensei , thanks for recommending these changes. Because this list is intended to serve as a one-stop roadmap for McCarthy associates that they can follow, we can't include very specific links or links that lead to other links or links to articles with more lists because it gets unorganized/out-of-date/out-of-hand pretty quickly. While we don't have a separate "Miscellaneous" section in this list, feel free to post helpful links like these on our slack channels. 😄

**Comment by SneakySensei** [comment]
Alright. This change was suggested by @vinayak19th.

**Comment by tnmygrwl** [comment]
Cool, I'll discuss it with him.  👍

**Comment by vinayak19th** [comment]
Yeah since there was relevant material for McCarthy, I told him to push it. I'll clean it up and push

**Comment by tnmygrwl** [comment]
Yeah, we should put in direct links to great courses or other resources on some broad category in AI covered exhaustively in the form of an article or something under their relevant headings. and we could put one-time reads and other cool cheat sheets/hacks/blogs etc. to slack channels.

**Comment by kausky** [comment]
If the cleanup is done, can we review and merge it ?

**Comment by tnmygrwl** [comment]
@Aakash-kaushik I think is great and there are loads of resources/links that could be useful, but this is intended as a comprehensive roadmap (a little outdated now, though) so it's better if we don't break the structure with miscellaneous stuff.

It would be great if we can add these to a separate list (google sheets?) and pin it under resources that can be updated by anyone and shared on slack. I am closing this PR for now. 👍

**Comment by tnmygrwl** [comment]
#10 check this issue out for more information.

**Comment by kausky** [comment]
@tanmay7270 Yeah seems like the right thing to do. :+1:

**Comment by tkrsh** [comment]
@tanmay7270 we can append some of the following under academic courses 

## Academic Courses 

- [Deep Learning (with Pytorch)](https://atcold.github.io/pytorch-Deep-Learning/)
  - DS-GA 1008: Deep Learning | SPRING 2020
- [Introduction to Deep Learning](http://introtodeeplearning.com/)
  - MIT 6.S191: Introduction to Deep Learning | 2020
- [CNNs for Visual Recognition](http://cs231n.stanford.edu)
  - CS231n: CNNs for Visual Recognition, Stanford | Spring 2019
- [NLP with Deep Learning](http://web.stanford.edu/class/cs224n/index.html#schedule)
  - CS224n: NLP with Deep Learning, Stanford | Winter 2019
- [Deep Reinforcement Learning](https://www.youtube.com/playlist?list=PLkFD6_40KJIwhWJpGazJ9VSj9CFMkb79A)
  - CS285: Deep Reinforcement Learning, UC Berkeley | Fall 2020
  - CS285: Deep Reinforcement Learning, UC Berkeley | Fall 2019
- [Unsupervised Learning](https://www.youtube.com/playlist?list=PLwRJQ4m4UJjPiJP3691u-qWwPGVKzSlNP)
  - CS294-158-SP20: Deep Unsupervised Learning, UC Berkeley | Spring 2020
- [Multi-Task and Meta Learning](https://www.youtube.com/playlist?list=PLoROMvodv4rMC6zfYmnD7UG3LVvwaITY5)
  - Stanford CS330: Multi-Task and Meta Learning | 2019

**Pull request closed without merging**
